In [1]:
import pandas as pd

In [4]:
# Step 1: Retrieve the dataset
df = pd.read_csv('Applications_for_Machine_Learning_internship_edited.xlsx - Sheet1.csv')
print(df)

      Name  Python (out of 3)  Machine Learning (out of 3)  \
0      NaN                  1                            0
1      NaN                  2                            0
2      NaN                  2                            2
3      NaN                  3                            2
4      NaN                  2                            2
...    ...                ...                          ...
1131   NaN                  2                            2
1132   NaN                  3                            3
1133   NaN                  3                            1
1134   NaN                  2                            1
1135   NaN                  2                            0

      Natural Language Processing (NLP) (out of 3)  Deep Learning (out of 3)  \
0                                                0                         1
1                                                0                         0
2                                                0                         0
3                                                2                         0
4                                                0                         0
...                                            ...                       ...
1131                                             0                         2
1132                                             2                         3
1133                                             3                         3
1134                                             0                         0
1135                                             0                         0

                                           Other skills  \
0     MS-Excel, MS-Word, Deep Learning, MySQL, Pytho...
1     Git, GitHub, Linux, Adobe After Effects, Adobe...
2     Amazon Web Services (AWS), Docker, Hadoop, MS-...
3     Adobe XD, BIG DATA ANALYTICS, Canva, Data Anal...
4     C++ Programming, Data Science, Machine Learnin...
...                                                 ...
1131  Data Analytics, Amazon Web Services (AWS), Dat...
1132  Deep Learning, Docker, HTML, MS-Office, Machin...
1133  Data Science, Deep Learning, English Proficien...
1134  Python, Data Analytics, MS-Excel, Machine Lear...
1135  C++ Programming, Database Management System (D...

     Are you available for 3 months, starting immediately, for a full-time work from home internship?   \
0     Yes, I am available for 3 months starting imme...
1     Yes, I am available for 3 months starting imme...
2     Yes, I am available for 3 months starting imme...
3     Yes, I am available for 3 months starting imme...
4     Yes, I am available for 3 months starting imme...
...                                                 ...
1131  Yes, I am available for 3 months starting imme...
1132  Yes, I am available for 3 months starting imme...
1133  Yes, I am available for 3 months starting imme...
1134  Yes, I am available for 3 months starting imme...
1135  Yes, I am available for 3 months starting imme...

                             Degree                          Stream  \
0     Bachelor of Vocation (B.Voc.)            Software Engineering
1                            B.Tech  Computer Science & Engineering
2          Master of Science (M.S.)      Data Science And Analytics
3     Bachelor of Engineering (B.E)                             NaN
4                            B.Tech                Computer Science
...                             ...                             ...
1131                         B.Tech          Mechanical Engineering
1132                         B.Tech  Computer Science & Engineering
1133                         B.Tech   Electronics and Communication
1134                         B.Tech                Computer Science
1135                         B.Tech                     Engineering

      Current Year Of Graduation Performance_PG Performance_UG Performance_12  \
0                           2021            NaN         6.50/7            NaN
1                           2024            NaN        8.90/10            NaN
2                           2022            NaN            NaN            NaN
3                           2024            NaN            NaN    85.60/85.60
4                           2023            NaN        8.10/10    93.40/93.40
...                          ...            ...            ...            ...
1131                        2021            NaN            NaN            NaN
1132                        2024            NaN            NaN            NaN
1133                        2025            NaN        8.77/10      9.40/9.40
1134                        2024            NaN        7.90/10    90.00/90.00
1135                        2024            NaN            NaN            NaN

     Performance_10
0               NaN
1               NaN
2               NaN
3       10.00/10.00
4       10.00/10.00
...             ...
1131            NaN
1132            NaN
1133            NaN
1134            NaN
1135            NaN

[1136 rows x 14 columns]

In [ ]:
# Step 2: Data preprocessing (cleaning and filtering)

# Assuming you want to remove any rows with missing values
dataset = df.dropna()

The data of the UG, PG, and 10th scores contains errors in them, data processing is needed.

In [20]:
# Step 3: Define evaluation criteria and weights
criteria_weights = {
    'Python': 0.2,
    'Machine Learning': 0.2,
    'Natural Language Processing (NLP)': 0.2,
    'Deep Learning': 0.2,
    'Other skills': 0.1,
    'Are you available for 3 months, starting immediately, for a full-time work from home internship?': 0.05,
    'Degree': 0.05,
    'Stream': 0.05,
    'Current Year Of Graduation': 0.025,
    'Performance_PG': 0.025,
    'Performance_UG': 0.025,
    'Performance_12': 0.025,
    'Performance_10': 0.025
}

In [ ]:
# Step 4: Normalize data (if required)
# Skip this step if the evaluation criteria are already on a common scale

I filtered the data with the requirements of availability of 3 months internships, 10th score > 8.00, 12th score > 70 and UG score>6.00 but changes can be made if the high scores are needed.

In [33]:
desired_streams = ['Computer Science', 'Software Engineering', 'Machine Learning', 'Computer Science & Engineering']
filtered_df = df[df['Stream'].isin(desired_streams)]
available = ['Yes, I am available for 3 months starting immediately for a full-time internship.']
filtered_df = filtered_df[filtered_df['Are you available for 3 months, starting immediately, for a full-time work from home internship? '].isin(available)]
filtered_df = filtered_df[filtered_df['Performance_10'] > '7.00/10.00']
filtered_df = filtered_df[filtered_df['Performance_12'] > '70.00/70.00']
filtered_df = filtered_df[filtered_df['Performance_UG'] > '6.00/10.00']

print(filtered_df)
len(filtered_df)

      Name  Python (out of 3)  Machine Learning (out of 3)  \
62     NaN                  2                            0
104    NaN                  2                            2
105    NaN                  3                            3
106    NaN                  3                            3
108    NaN                  1                            1
142    NaN                  2                            2
187    NaN                  2                            0
259    NaN                  2                            2
277    NaN                  2                            1
328    NaN                  3                            2
357    NaN                  2                            2
399    NaN                  0                            0
476    NaN                  3                            2
497    NaN                  2                            2
553    NaN                  2                            1
558    NaN                  2                            2
561    NaN                  3                            3
562    NaN                  2                            1
565    NaN                  2                            2
572    NaN                  0                            2
638    NaN                  3                            0
639    NaN                  2                            1
640    NaN                  3                            3
642    NaN                  2                            2
672    NaN                  2                            1
682    NaN                  0                            0
726    NaN                  2                            2
738    NaN                  2                            3
753    NaN                  3                            0
764    NaN                  1                            0
774    NaN                  3                            2
852    NaN                  3                            2
897    NaN                  3                            2
906    NaN                  3                            0
986    NaN                  2                            2
988    NaN                  2                            2
1014   NaN                  2                            2
1021   NaN                  2                            0
1074   NaN                  2                            2
1083   NaN                  3                            3
1084   NaN                  2                            3

      Natural Language Processing (NLP) (out of 3)  Deep Learning (out of 3)  \
62                                               0                         0
104                                              0                         2
105                                              1                         2
106                                              2                         2
108                                              0                         0
142                                              1                         1
187                                              0                         0
259                                              2                         2
277                                              0                         0
328                                              0                         2
357                                              0                         0
399                                              0                         0
476                                              0                         2
497                                              0                         0
553                                              0                         1
558                                              1                         1
561                                              2                         2
562                                              0                         0
565                                              2                         0
572                                              0                         2
638                                              0                         0
639                                              0                         0
640                                              2                         3
642                                              0                         1
672                                              0                         1
682                                              0                         0
726                                              2                         2
738                                              2                         1
753                                              0                         0
764                                              0                         0
774                                              2                         2
852                                              0                         2
897                                              0                         0
906                                              0                         0
986                                              0                         0
988                                              0                         1
1014                                             2                         0
1021                                             0                         0
1074                                             0                         0
1083                                             0                         1
1084                                             2                         2

                                           Other skills  \
62    CSS, Creative Writing, English Proficiency (Sp...
104   C Programming, Data Science, Data Structures, ...
105   Data Analytics, Data Science, English Proficie...
106   CSS, Express.js, HTML, JavaScript, MEAN/MERN S...
108   CSS, English Proficiency (Spoken), English Pro...
142   C Programming, Content Writing, Database Manag...
187   C Programming, English Proficiency (Spoken), A...
259   American English, English Proficiency (Spoken)...
277   C++ Programming, Data Structures, MS-PowerPoin...
328   Java, MS-Excel, Python, CSS, Computer Vision, ...
357   C Programming, C++ Programming, Data Science, ...
399                                                 NaN
476   Python, C Programming, C++ Programming, Data A...
497   CSS, HTML, C++ Programming, Data Analytics, Ja...
553   Data Structures, Python, Deep Learning, Flask,...
558   Data Analytics, Data Science, Data Structures,...
561   Data Science, MS-Excel, Machine Learning, Powe...
562   HTML, Algorithms, C++ Programming, Data Struct...
565   Artificial intelligence, C Programming, C++ Pr...
572   C Programming, English Proficiency (Spoken), E...
638   C Programming, C++ Programming, MS-Excel, MS-O...
639   English Proficiency (Written), Python, Bootstr...
640   Data Analytics, Deep Learning, Machine Learnin...
642   CSS, HTML, C Programming, C++ Programming, Ima...
672       Java, Python, Deep Learning, Machine Learning
682   C++ Programming, CSS, Creative Writing, Englis...
726   Data Analytics, MS-Excel, SQL, Data Science, D...
738   Machine Learning, Algorithms, Artificial intel...
753                    C Programming, Python, SQL, Java
764   C Programming, C++ Programming, CSS, HTML, Jav...
774   Data Analytics, Python, Data Science, Deep Lea...
852   CSS, HTML, MySQL, Python, VS Code, C Programmi...
897   Python, Artificial Intelligence, CSS, Data Str...
906   Python, Adobe Photoshop, C Programming, C++ Pr...
986   Machine Learning, OpenCV, Python, Android, GitHub
988   Data Science, English Proficiency (Written), M...
1014  Node.js, SQL, .NET, Algorithms, Angular 7.0, A...
1021  C Programming, MS-Word, C++ Programming, CSS, ...
1074  C Programming, CSS, Database Management System...
1083  Computer Vision, Data Analytics, English Profi...
1084  Cloud Computing, Data Science, Data Structures...

     Are you available for 3 months, starting immediately, for a full-time work from home internship?   \
62    Yes, I am available for 3 months starting imme...
104   Yes, I am available for 3 months starting imme...
105   Yes, I am available for 3 months starting imme...
106   Yes, I am available for 3 months starting imme...
108   Yes, I am available for 3 months starting imme...
142   Yes, I am available for 3 months starting imme...
187   Yes, I am available for 3 months starting imme...
259   Yes, I am available for 3 months starting imme...
277   Yes, I am available for 3 months starting imme...
328   Yes, I am available for 3 months starting imme...
357   Yes, I am available for 3 months starting imme...
399   Yes, I am available for 3 months starting imme...
476   Yes, I am available for 3 months starting imme...
497   Yes, I am available for 3 months starting imme...
553   Yes, I am available for 3 months starting imme...
558   Yes, I am available for 3 months starting imme...
561   Yes, I am available for 3 months starting imme...
562   Yes, I am available for 3 months starting imme...
565   Yes, I am available for 3 months starting imme...
572   Yes, I am available for 3 months starting imme...
638   Yes, I am available for 3 months starting imme...
639   Yes, I am available for 3 months starting imme...
640   Yes, I am available for 3 months starting imme...
642   Yes, I am available for 3 months starting imme...
672   Yes, I am available for 3 months starting imme...
682   Yes, I am available for 3 months starting imme...
726   Yes, I am available for 3 months starting imme...
738   Yes, I am available for 3 months starting imme...
753   Yes, I am available for 3 months starting imme...
764   Yes, I am available for 3 months starting imme...
774   Yes, I am available for 3 months starting imme...
852   Yes, I am available for 3 months starting imme...
897   Yes, I am available for 3 months starting imme...
906   Yes, I am available for 3 months starting imme...
986   Yes, I am available for 3 months starting imme...
988   Yes, I am available for 3 months starting imme...
1014  Yes, I am available for 3 months starting imme...
1021  Yes, I am available for 3 months starting imme...
1074  Yes, I am available for 3 months starting imme...
1083  Yes, I am available for 3 months starting imme...
1084  Yes, I am available for 3 months starting imme...

                                     Degree                          Stream  \
62                                   B.Tech  Computer Science & Engineering
104                                  B.Tech  Computer Science & Engineering
105                                  B.Tech                Computer Science
106                Master of Science (M.Sc)                Computer Science
108                          B.Tech (Hons.)  Computer Science & Engineering
142         Bachelor of Technology (B.Tech)  Computer Science & Engineering
187                                  B.Tech  Computer Science & Engineering
259                                  B.Tech                Computer Science
277         Bachelor of Technology (B.Tech)                Computer Science
328   Bachelor of Engineering (B.E) (Hons.)  Computer Science & Engineering
357                                  B.Tech                Computer Science
399                                  B.Tech  Computer Science & Engineering
476                                  B.Tech  Computer Science & Engineering
497                                  B.Tech  Computer Science & Engineering
553        Bachelor of Computer Engineering                Computer Science
558                                  B.Tech                Computer Science
561              Bachelor of Science (B.Sc)                Computer Science
562                                  B.Tech  Computer Science & Engineering
565           Bachelor of Engineering (B.E)  Computer Science & Engineering
572                                  B.Tech                Computer Science
638                                  B.Tech  Computer Science & Engineering
639         Bachelor of Technology (B.Tech)  Computer Science & Engineering
640                          B.Tech (Hons.)                Machine Learning
642                          B.Tech (Hons.)  Computer Science & Engineering
672           Master of Technology (M.Tech)                Computer Science
682      Bachelor of Science (B.Sc) (Hons.)                Computer Science
726                                  B.Tech  Computer Science & Engineering
738         Bachelor of Technology (B.Tech)  Computer Science & Engineering
753                                  B.Tech  Computer Science & Engineering
764                                  B.Tech  Computer Science & Engineering
774      Bachelor of Science (B.Sc) (Hons.)                Computer Science
852         Bachelor of Technology (B.Tech)  Computer Science & Engineering
897         Bachelor of Technology (B.Tech)                Computer Science
906           Bachelor of Engineering (B.E)  Computer Science & Engineering
986                                  B.Tech                Computer Science
988                                  B.Tech  Computer Science & Engineering
1014  Master of Computer Applications (MCA)  Computer Science & Engineering
1021                                 B.Tech  Computer Science & Engineering
1074                                 B.Tech                Computer Science
1083                                 B.Tech  Computer Science & Engineering
1084                                 B.Tech  Computer Science & Engineering

      Current Year Of Graduation Performance_PG Performance_UG Performance_12  \
62                          2023            NaN        7.55/10      9.50/9.50
104                         2023            NaN        9.20/10    84.66/84.66
105                         2024            NaN        7.51/10    89.60/89.60
106                         2023            NaN        9.75/10    75.23/75.23
108                         2023            NaN        8.90/10    88.70/88.70
142                         2024            NaN        8.48/10    91.40/91.40
187                         2024            NaN        9.54/10    94.00/94.00
259                         2024            NaN        7.86/10    88.67/88.67
277                         2025            NaN        7.58/10    78.60/78.60
328                         2024            NaN        8.52/10    90.40/90.40
357                         2025            NaN        9.53/10    82.40/82.40
399                         2024            NaN        8.00/10      8.00/8.00
476                         2024            NaN        8.41/10    84.00/84.00
497                         2023            NaN        8.40/10    74.00/74.00
553                         2021            NaN      72.00/100    71.08/71.08
558                         2023            NaN        9.09/10    91.00/91.00
561                         2020            NaN        6.40/10      8.40/8.40
562                         2024            NaN        8.04/10    89.00/89.00
565                         2022            NaN       8.00/100      9.40/9.40
572                         2023            NaN        8.67/10      9.10/9.10
638                         2024            NaN        8.56/10    95.80/95.80
639                         2023            NaN        8.26/10    94.00/94.00
640                         2023            NaN        7.50/10    80.00/80.00
642                         2023            NaN        8.97/10    79.90/79.90
672                         2022        7.59/10        6.97/10    75.00/75.00
682                         2023            NaN        9.40/10    95.00/95.00
726                         2023            NaN         7.00/7      9.50/9.50
738                         2023            NaN        7.60/10    78.00/78.00
753                         2023            NaN        8.00/10    71.08/71.08
764                         2025            NaN        9.10/10    90.00/90.00
774                         2021            NaN        7.80/10    92.00/92.00
852                         2025            NaN        9.09/10    88.40/88.40
897                         2023            NaN        8.00/10      9.67/9.67
906                         2025            NaN      95.00/100    94.40/94.40
986                         2025            NaN        8.97/10    96.70/96.70
988                         2023            NaN        8.80/10    81.69/81.69
1014                        2017        7.67/10      66.75/100    77.80/77.80
1021                        2024            NaN        9.00/10      9.25/9.25
1074                        2023            NaN        7.00/10      9.73/9.73
1083                        2024            NaN        8.46/10    86.00/86.00
1084                        2024            NaN        9.07/10    97.30/97.30

     Performance_10
62        9.70/9.70
104     94.88/94.88
105     91.00/91.00
106     87.40/87.40
108     92.30/92.30
142     95.20/95.20
187     93.40/93.40
259     93.67/93.67
277     87.40/87.40
328     90.20/90.20
357     88.60/88.60
399       8.00/8.00
476     76.00/76.00
497       8.40/8.40
553     87.00/87.00
558     90.00/90.00
561       8.20/8.20
562       9.00/9.00
565       9.20/9.20
572       9.40/9.40
638     92.60/92.60
639     95.00/95.00
640       9.00/9.00
642       9.40/9.40
672     73.00/73.00
682     80.20/80.20
726       8.80/8.80
738       8.20/8.20
753     84.20/84.20
764     86.17/86.17
774       9.20/9.20
852     89.20/89.20
897       9.80/9.80
906     94.40/94.40
986     96.67/96.67
988     93.60/93.60
1014    79.75/79.75
1021      9.80/9.80
1074      9.00/9.00
1083    92.20/92.20
1084      9.80/9.80

41

In [35]:
# Step 5: Calculate scores
filtered_df['score'] = (
    filtered_df['Python (out of 3)'] * criteria_weights['Python'] +
    filtered_df['Machine Learning (out of 3)'] * criteria_weights['Machine Learning'] +
    filtered_df['Natural Language Processing (NLP) (out of 3)'] * criteria_weights['Natural Language Processing (NLP)'] +
    filtered_df['Deep Learning (out of 3)'] * criteria_weights['Deep Learning']

)
# for column, weight in criteria_weights.items():
#     if column in df.columns:
#         df[column] = df[column].fillna('')  # Replace NaN values with empty string for consistency
#         df['score'] += df[column].apply(lambda x: weight if x.strip().lower() != '' else 0)

In [36]:
# Step 6: Rank the interns
ranked_dataset = filtered_df.sort_values("score", ascending=False)

In [37]:
# Step 7: Interview and selection
# Proceed with the interview process based on the ranked dataset

# Print the top-ranked intern
top_intern = ranked_dataset.iloc[0]
print("Top-ranked intern:")
print(top_intern)

Top-ranked intern:
Name                                                                                                                                               NaN
Python (out of 3)                                                                                                                                    3
Machine Learning (out of 3)                                                                                                                          3
Natural Language Processing (NLP) (out of 3)                                                                                                         2
Deep Learning (out of 3)                                                                                                                             3
Other skills                                                                                         Data Analytics, Deep Learning, Machine Learnin...
Are you available for 3 months, starting immediately, for a full-time work from home internship?     Yes, I am available for 3 months starting imme...
Degree                                                                                                                                  B.Tech (Hons.)
Stream                                                                                                                                Machine Learning
Current Year Of Graduation                                                                                                                        2023
Performance_PG                                                                                                                                     NaN
Performance_UG                                                                                                                                 7.50/10
Performance_12                                                                                                                             80.00/80.00
Performance_10                                                                                                                               9.00/9.00
score                                                                                                                                              2.2
Name: 640, dtype: object